# Feature Engineering

---

1. Import packages
2. Load data
3. Feature engineering

---

## 1. Import packages

In [2]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

---
## 2. Load data

In [10]:
df = pd.read_csv('client_data.csv')
df["date_activ"] = pd.to_datetime(df["date_activ"], format='%Y-%m-%d')
df["date_end"] = pd.to_datetime(df["date_end"], format='%Y-%m-%d')
df["date_modif_prod"] = pd.to_datetime(df["date_modif_prod"], format='%Y-%m-%d')
df["date_renewal"] = pd.to_datetime(df["date_renewal"], format='%Y-%m-%d')
df =df.drop(columns=['origin_up','channel_sales'])
df['has_gas'] = df['has_gas'].replace({'t': 1, 'f': 0})

In [18]:
df

,id,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,...,forecast_price_pow_off_peak,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,pow_max,churn
0,24011ae4ebbe3035111d65fa7c15bc57,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,...,40.606701,1,0.00,25.44,25.44,2,678.99,3,43.648,1
1,d29c2c54acc38ff3c0614d0a653813dd,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,...,44.311378,0,0.00,16.38,16.38,1,18.89,6,13.800,0
2,764c75f661154dac3a6c254cd082ea7d,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,...,44.311378,0,0.00,28.60,28.60,1,6.60,6,13.856,0
3,bba03439a292a1e166f80264c16191cb,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,...,44.311378,0,0.00,30.22,30.22,1,25.46,6,13.200,0
4,149d57cf92fc41cf94415803a877cb4b,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,...,40.606701,0,52.32,44.91,44.91,1,47.98,6,19.800,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,18463073fb097fc0ac5d3e040f356987,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,0,...,44.311378,1,0.00,27.88,27.88,2,381.77,4,15.000,0
14602,d0a6f71671571ed83b2645d23af6de00,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,181,...,58.995952,0,15.94,0.00,0.00,1,90.34,3,6.000,1
14603,10e6828ddd62cbcf687cb74928c4c2d2,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,179,...,40.606701,0,18.05,39.84,39.84,1,20.38,4,15.935,1
14604,1cf20fd6206d7678d5bcafd28c53b4db,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,0,...,44.311378,0,0.00,13.08,13.08,1,0.96,3,11.000,0
14605,563dde550fd624d7352f3de77c0cdfcd,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,0,...,45.311378,0,0.00,11.84,11.84,1,96.34,6,10.392,0

---

## 3. Feature engineering

### Difference between off-peak prices in December and preceding January

Below is the code created by your colleague to calculate the feature described above. Use this code to re-create this feature and then think about ways to build on this feature to create features with a higher predictive power.

In [7]:
price_df = pd.read_csv('price_data.csv')
price_df["price_date"] = pd.to_datetime(price_df["price_date"], format='%Y-%m-%d')
price_df.head()

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.151367,0.0,0.0,44.266931,0.0,0.0
1,038af19179925da21a25619c5a24b745,2015-02-01,0.151367,0.0,0.0,44.266931,0.0,0.0
2,038af19179925da21a25619c5a24b745,2015-03-01,0.151367,0.0,0.0,44.266931,0.0,0.0
3,038af19179925da21a25619c5a24b745,2015-04-01,0.149626,0.0,0.0,44.266931,0.0,0.0
4,038af19179925da21a25619c5a24b745,2015-05-01,0.149626,0.0,0.0,44.266931,0.0,0.0

In [24]:
# Group off-peak prices by companies and month
monthly_price_by_id = price_df.groupby(['id', 'price_date']).agg({'price_off_peak_var': 'mean', 'price_off_peak_fix': 'mean'}).reset_index()

# Get january and december prices
jan_prices = monthly_price_by_id.groupby('id').first().reset_index()
dec_prices = monthly_price_by_id.groupby('id').last().reset_index()

# Calculate the difference
diff = pd.merge(dec_prices.rename(columns={'price_off_peak_var': 'dec_1', 'price_off_peak_fix': 'dec_2'}), jan_prices.drop(columns='price_date'), on='id')
diff['offpeak_diff_dec_january_energy'] = diff['dec_1'] - diff['price_off_peak_var']
diff['offpeak_diff_dec_january_power'] = diff['dec_2'] - diff['price_off_peak_fix']
diff = diff[['id', 'offpeak_diff_dec_january_energy','offpeak_diff_dec_january_power']]
diff.shape

(16096, 3)

In [25]:
merged_df = pd.merge(df, diff, on='id', how='inner')

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x= merged_df.drop(columns=['id','churn','date_activ','date_end','date_modif_prod','date_renewal'])
y = df['churn']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [37]:
randomf =RandomForestClassifier()
randomf.fit(X_train,y_train)

RandomForestClassifier()

In [38]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [39]:
y_pred = randomf.predict(X_test)

In [42]:
accu = randomf.score(X_test, y_test)
accu

0.8980150581793293

In [43]:
confusion_matrix(y_test,y_pred)

array([[2611,    3],
       [ 295,   13]], dtype=int64)

In [45]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95      2614
           1       0.81      0.04      0.08       308

    accuracy                           0.90      2922
   macro avg       0.86      0.52      0.51      2922
weighted avg       0.89      0.90      0.85      2922